require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end


def all_pods
  config = use_native_modules!

  # React Native 0.80 compatible configuration - removed deprecated get_default_flags()
  use_react_native!(
    :path => "../../node_modules/react-native",
    :hermes_enabled => true,
    :fabric_enabled => true,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/../.."
  )

  pod 'ReactNativeNavigation', :path => '../../'
  pod 'HMSegmentedControl'
end

post_install do |installer|
  react_native_post_install(installer, "../../node_modules/react-native", :mac_catalyst_enabled => false)

  # React Native 0.80 Folly coroutine compatibility fix (proven production solution)
  system("chmod -R u+w Pods/RCT-Folly")
  Dir.glob("Pods/RCT-Folly/folly/Portability.h").each do |file|
    text = File.read(file)
    new_contents = text.gsub('#define FOLLY_HAS_COROUTINES 1', '#define FOLLY_HAS_COROUTINES 0')
    File.open(file, "w") { |file| file.puts new_contents }
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
      config.build_settings['HEADER_SEARCH_PATHS'] << '$(PODS_ROOT)/Headers/Public/React-hermes'
      
      # React Native 0.80 iOS build requirements
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end

  installer.pods_project.build_configurations.each do |config|
    config.build_settings['USE_HERMES'] = '1'  # Ensure Hermes is enabled
  end
end

target 'playground' do
  all_pods
end

target 'NavigationTests' do
  all_pods
  pod 'OCMock'
end

target 'NavigationIOS12Tests' do
  all_pods
  pod 'OCMock'
end

target 'SnapshotTests' do
  all_pods
  pod 'OCMock'
end
